version: '3'
services:
  postgres:
    image: postgres:14.2
    restart: unless-stopped
    ports:
      - "9432:5432"
    environment:
      POSTGRES_DB: "shop"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "0810923"